spring:
  application:
    name: moodtree
server:
  port: 8866

third_api:
  chatglm:
    url: https://chatglm.cn/chatglm/assistant-api/v1
    key: 7236fd914267180e
    secret: 6dfcf6ba8e3ebb2524fe7168b4a9ad96
    mood_therapy_api_id: 6789d124edd4a13c4571b2d6
    mood_analysis_api_id: 6791a39c2db09f54cb8333a9